/*
LeetCode Problem: https://leetcode.com/problems/find-the-length-of-the-longest-common-prefix/

Question: 3043. Find the Length of the Longest Common Prefix

Problem Statement: You are given two arrays with positive integers arr1 and arr2.

A prefix of a positive integer is an integer formed by one or more of its digits, starting from its leftmost digit. For example, 123 is a prefix of the integer 12345, while 234 is not.

A common prefix of two integers a and b is an integer c, such that c is a prefix of both a and b. For example, 5655359 and 56554 have common prefixes 565 and 5655 while 1223 and 43456 do not have a common prefix.

You need to find the length of the longest common prefix between all pairs of integers (x, y) such that x belongs to arr1 and y belongs to arr2.

Return the length of the longest common prefix among all pairs. If no common prefix exists among them, return 0.

Example 1:
Input: arr1 = [1,10,100], arr2 = [1000]
Output: 3
Explanation: There are 3 pairs (arr1[i], arr2[j]):
- The longest common prefix of (1, 1000) is 1.
- The longest common prefix of (10, 1000) is 10.
- The longest common prefix of (100, 1000) is 100.
The longest common prefix is 100 with a length of 3.

Example 2:
Input: arr1 = [1,2,3], arr2 = [4,4,4]
Output: 0
Explanation: There exists no common prefix for any pair (arr1[i], arr2[j]), hence we return 0.
Note that common prefixes between elements of the same array do not count.

Constraints:
1 <= arr1.length, arr2.length <= 5 * 10^4
1 <= arr1[i], arr2[i] <= 10^8
*/

/*
Approach: Prefix Reduction + HashSet Lookup

Goal:
- Find the maximum length of a common numeric prefix
  between any pair of numbers from arr1 and arr2.

Core Idea:
- Every prefix of a number can be generated by
  repeatedly dividing by 10.
- Store all prefixes from arr1 in a HashSet.
- For each number in arr2:
   - Reduce digit-by-digit until a matching prefix is found.
- Track the maximum prefix length.

Algorithm Steps:
1. Traverse arr1:
   - Insert all prefixes of each number into HashSet.
2. Traverse arr2:
   - Generate prefixes by dividing by 10.
   - If prefix exists in set:
       - Compute digit length of prefix.
       - Update maximum length.
       - Break current search.
3. Return longest common prefix length.

Time Complexity:
- O(n * d + m * d)
  where d = number of digits

Space Complexity:
- O(n * d)

Result:
- Returns length of the longest common numeric prefix.
*/

package Arrays.Medium;

import java.util.HashSet;

// Solution Class
class Solution {
    // Method to find the length of the longest common prefix among all pairs
    public int longestCommonPrefix(int[] arr1, int[] arr2) {
        // Initialize the hashset for the keeping the values
        HashSet<Integer> set = new HashSet<>();

        // Iterate over the arr1 to fill the set array
        for (int i = 0; i < arr1.length; i++) {
            // Add all the prefix of the current index of the arr1 untill it become zero
            while (arr1[i] != 0) {
                // If arr1[i] is in the set then break out of the loop
                if (set.contains(arr1[i])) {
                    break;
                }

                // Add the value to the set
                set.add(arr1[i]);

                // Update the number
                arr1[i] /= 10;
            }
        }

        // Initialize the longest common prefix varaible
        int longestCommonPrefix = 0;

        // Iterate over the arr2 to get the longest common prefix
        for (int i = 0; i < arr2.length; i++) {
            // Check all the prefix of teh current index of the arr2 untill it become zero
            while (arr2[i] != 0) {
                // If arr2[i] is in the set then check the length of the prefix and break out of
                // the loop
                if (set.contains(arr2[i])) {
                    // Initialize the length variable
                    int length = 0;

                    // Get the length of the arr2[i]
                    while (arr2[i] != 0) {
                        // Update the number
                        arr2[i] /= 10;

                        // Increment the length value
                        length++;
                    }

                    // Update the longest common prefix varaible
                    longestCommonPrefix = Math.max(longestCommonPrefix, length);

                    // Break out of the loop
                    break;
                }

                // Update the number
                arr2[i] /= 10;
            }
        }

        // Return the longest common prefix
        return longestCommonPrefix;
    }
}

public class _3043_Find_the_Length_of_the_Longest_Common_Prefix {
    // Main method to test longestCommonPrefix
    public static void main(String[] args) {
        int[] arr1 = new int[] { 1, 10, 100 };
        int[] arr2 = new int[] { 1000 };

        int result = new Solution().longestCommonPrefix(arr1, arr2);

        System.out.println("The length of the longest common prefix among all pairs is : " + result);
    }
}
